# commit to be tagged for the new release
commit = "HEAD"

project_name = "terraform-provider-talos"
github_repo = "siderolabs/terraform-provider-talos"
ignore_deps = ["google.golang.org/grpc"]

previous = "v0.10.1"
pre_release = false

[notes]

    [notes.updates]
        title = "Component Updates"
        description = """\
Talos sdk: v1.13.0
"""

    [notes.config_patches]
        title = "ephemeral resources"
        description = """\
New ephemeral resources are added, please see docs.
"""
